version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  api:
    build: ../tyt-api-repo/
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    restart: always
    ports:
      - 8081:8081